name: Update Crypto Report

on:
  schedule:
    - cron: "0 * * * *"  # اجرا هر ساعت
  workflow_dispatch:  # اجرای دستی در صورت نیاز

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Python Script
        run: python update_readme.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "📊 آپدیت قیمت‌های کریپتو $(date)"
          git push
        continue-on-error: true  # جلوگیری از خطا در صورت نبود تغییرات
